### ISSUE TITLE
Generate Invoice via legend.lnbits.com API: 'NoneType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by altoidkind** [lnbits/lnbits-legend#371]
I'm trying to call the creation of an invoice using cURL, which is specified in the API documentation:

`curl -X POST https://legend.lnbits.com/api/v1/payments -d '{"out": false, "amount": 1, "memo": "testmemo"}' -H "my_api_key" -H "Content-type: application/json"`

And it gives an error: 'NoneType' object has no attribute 'upper'

I think this happened after commit `1fb2fee99bc4c54072ec5836e0760a3a8766dbcb`, before that everything was working fine.

**Comment by talvasconcelos** [comment]
I believe the error you're getting is a badly formed request:

`curl -X POST https://legend.lnbits.com/api/v1/payments -d '{"out": false, "amount": 1, "memo": "testmemo"}' -H "X-Api-Key: my_api_key" -H "Content-type: application/json"` - notice the `X-Api-Key: ` !! You should pass a key: value pair!
