### ISSUE TITLE
Bleskomat on legend.lnbits.com is throwing Unknown Error

### ISSUE THREAD

**Issue by webiumsk** [lnbits/lnbits-legend#401]
By scanning QR from Bleskomat, there is an Unknown Error. I tried Phoenix, Blue, Zap, ... 
(I have changed config to callbackUrl = "https://legend.lnbits.com/bleskomat/u"; )

On my own node with older version of lnbits everything works. 

Any suggestions?

**Comment by relcead** [comment]
Hello,

i have the same issue while testing https://legend.lnbits.com/bleskomat/u.
The SBW wallet is responding: "java.lang.Exception:Error from vendor: Unexpected error"

Thank you great project.

**Comment by chill117** [comment]
I confirm the problem as reported by the others. I will try to get a local instance of lnbits running so that I can debug and fix the problem.

**Comment by chill117** [comment]
It looks like the fix has been deployed to the public instance at legend.lnbits.com so I think this issue can be closed.

**Comment by webiumsk** [comment]
Yep. It's working. Thank you.
