### ISSUE TITLE
Split Payments Extension Not Firing Split Events on core api send_events

### ISSUE THREAD

**Issue by claytantor** [lnbits/lnbits-legend#425]
Commit version: `e6bf9797a4f5e04c75d341256274deb47e352d0f`

This is not happening for me. 

`When the source wallet receives a payment, the extension will automatically split the corresponding values to every wallet`

The invoice paid event never gets fired, even though the listener is registered... 

what I am expecting is that when core api calls the `send_events` method
```
    async def send_events():
        print("send_events")
        try:
            async for typ, data in event_to_send:
                message = [f"event: {typ}".encode("utf-8")]

                if data:
                    jdata = json.dumps(dict(data._asdict(), pending=False))
                    message.append(f"data: {jdata}".encode("utf-8"))

                yield b"\n".join(message) + b"\r\n\r\n"
        except trio.Cancelled:
            return
```
that the splt payment on payment event is fired

```
async def on_invoice_paid(payment: Payment) -> None:
    print(f"on_invoice_paid: {payment}")
    if "splitpayments" == payment.extra.get("tag") or payment.extra.get("splitted"):
        # already splitted, ignore
        return
```

This is not occurring, the transaction settles as if there were no registered splits:

```
check_invoice_status services
 - marking 'in' lntx_2iBumwlR97nqZZ5W54l7pAX as not pending anymore: settled
```

**Comment by fiatjaf** [comment]
What is the funding source?

**Comment by claytantor** [comment]
> What is the funding source?

LNPay

**Comment by fiatjaf** [comment]
For LNPay you must set up webhooks manually otherwise none of the reactive things will work. Please see the docs somewhere I don't remember for more information.

**Comment by fiatjaf** [comment]
https://github.com/lnbits/lnbits-legend/blob/master/docs/guide/wallets.md#lnpay

**Comment by claytantor** [comment]
> For LNPay you must set up webhooks manually otherwise none of the reactive things will work. Please see the docs somewhere I don't remember for more information.

HELPFUL! Will attempt and reopen a different issues if I find.
