### ISSUE TITLE
LNURLp: Allow to configure metadata

### ISSUE THREAD

**Issue by iBobik** [lnbits/lnbits-legend#426]
There are multiple features like [e-mail address like identificator](https://github.com/fiatjaf/lnurl-rfc/blob/luds/16.md) or [image and long description](https://github.com/fiatjaf/lnurl-rfc/blob/luds/06.md) in LNURL-pay standard.

Could LNbits support all of this by configuring metadata field?

**Comment by arcbtc** [comment]
Yes, added to the list, but will take while yo get there. Prs very welcome

**Comment by iBobik** [comment]
I will maybe try to implement this. What approach is more welcome?

1. Offer to write custom metadata JSON in one textarea (+ JSON validation)
2. Make form fields for all currently available metadatas (especially images could be harder to impelement)
