### ISSUE TITLE
lnurl withdrawal allow uses more than specific in the amount of uses

### ISSUE THREAD

**Issue by javad94** [lnbits/lnbits-legend#439]
Hi, why Lnbits allow users to use withdraw lnurl more than specified in the amount of uses field?

lnurl withdrawal setting:
![image](https://user-images.githubusercontent.com/7765309/143792902-69120a01-a619-478b-a0ee-b4253affb0fb.png)

uses history:
![image](https://user-images.githubusercontent.com/7765309/143792930-6458eaac-0fb1-419d-9f98-a16088dc85fa.png)

**Comment by arcbtc** [comment]
Fixed in latest FastAPI branch, soon to be made master

**Comment by javad94** [comment]
> Fixed in latest FastAPI branch, soon to be made master

Thank you. Will check that.
