### ISSUE TITLE
Silly Question: Drain Funds

### ISSUE THREAD

**Issue by bstin** [lnbits/lnbits-legend#445]
Is there a special way to create a "drain funds" qr-code programatically? Or is this just a regular LNURL-w with a really high maximum set?

**Comment by fiatjaf** [comment]
It is a special static QR code.

**Comment by bstin** [comment]
Is it possible to make one via API? Or otherwise how does one access it programatically?

**Comment by fiatjaf** [comment]
It's always the same, how can you "make" one? Just copy the one you have.

**Comment by fiatjaf** [comment]
Take the LNURL string and decode it here: https://lnurl.fiatjaf.com/codec/

**Comment by bstin** [comment]
Thank you!
