### ISSUE TITLE
Internal Transfer Question

### ISSUE THREAD

**Issue by bstin** [lnbits/lnbits-legend#449]
NOTE: Sorry to use github as place to ask questions, but I can't access Telegram from work and I'm not aware of any other way to contact devs / users. 

I'm building an app that is utilizing UserManager extension in lnbits. I'm looking for a way for an EXTERNAL application (ie. not a lnbits extension) to transfer amounts between 2 user wallets. 

Obviously I could manually "create" and "pay" actual LN invoices, but this seems needlessly complex and slow as I'm only trying to shuffle balances around. 

Is there a way I could accomplish this using externally available API?

**Comment by arcbtc** [comment]
When you transfer money between lnbits wallets it basically fakes the transaction  internally
