### ISSUE TITLE
 invoice error with COP currency

### ISSUE THREAD

**Issue by richardelima** [lnbits/lnbits-legend#452]
lightningd 'invoice' failed with '{'code': -32602, 'message': "msatoshi: should be positive msat or 'any': invalid token '0'"}'.
520

**Comment by talvasconcelos** [comment]
i believe i sent a fix for that, unfortunately, the COP is less than 1 sat and it causes some errors! you are trying to get an invoice with 0 amount!

**Comment by richardelima** [comment]
Hi!. With infinity the invoice works fine with COP.
with legend still error exists. It is curious that pos plugin works fine.
Even with small values

By the way, how to activate pos plugin with infinity?. I have search but no
info about what to fill in module URL.

thanks!

**Comment by arcbtc** [comment]
this has been fixed with this pr https://github.com/lnbits/lnbits-legend/pull/480
