### ISSUE TITLE
No webhook call after receiving payment on LNBits instance with funding source LNBits

### ISSUE THREAD

**Issue by cryptoteun** [lnbits/lnbits-legend#487]
When I perform a payment to an invoice with a webhook configured, no webhook call is triggered after the payment is received. 
Below the details of a test on legend (Commit version: 93e58f4c807006c26b675f34947a5bda9743cd86)

The webhook state remains: not sent yet

> Date:  2022-01-08 20:37 (2 minutes ago)
> Description: Test legend - Test
> Amount: 5.000 sat
> Fee: 0.000 sat
> Payment hash: 841720c97d43eaa833908fb8c2585199579ded6eefed97b0f86090fe5eb4d29d
> Webhook: https://<secret>.ngrok.io/webhook/paymentstatus/558Hb3LQ/ not sent yet

**Comment by dni** [comment]
i noticed that too

**Comment by lylepratt** [comment]
I'm unable to get webhooks to work on invoices created against wallets @ legend.lnbits.com. Is legend.lnbits.com using LNBits as the funding source?

**Comment by cryptoteun** [comment]
@callebtc , is it possible the issue is somehow related to the one already fixed here? 
https://github.com/lnbits/lnbits-legend/pull/649

**Comment by cryptoteun** [comment]
> 

unfortunately for me its still not working. No error, nothing. 
If someone have an idea on how to debug ( i run via docker), please let me know

**Comment by callebtc** [comment]
Sorry for chiming in so late. Please `git pull` to the newest version and follow the [installation procedure](https://github.com/lnbits/lnbits-legend/blob/main/docs/guide/installation.md#option-1-poetry) for the new `poetry` package manager that we're using. Webhooks should be fixed now.

Feel free to reopen this issue should you still experience problems! Cheers
