### ISSUE TITLE
Do you guys cut new releases to myNode?

### ISSUE THREAD

**Issue by mjschmidt** [lnbits/lnbits-legend#493]
I was trying out myNode distribution of lightning and I love the capabilities of lnbits, I was wondering if you guys are the ones that release new versions onto myNode, or if that was myNode itself.

Thanks!

**Comment by arcbtc** [comment]
Its mynode itself

**Comment by arcbtc** [comment]
You could bug them to update to https://github.com/lnbits/lnbits-legend/releases/tag/0.5.0
