### ISSUE TITLE
Any way to contact for security vulnerabilities?

### ISSUE THREAD

**Issue by Semisol** [lnbits/lnbits-legend#547]
Please give an email if possible. Or please reach out to `hi at semisol dot dev`.

**Comment by arcbtc** [comment]
Good call

**Comment by arcbtc** [comment]
Done https://github.com/lnbits/lnbits-legend/blob/main/README.md#lnbits-v03-beta-free-and-open-source-lightning-network-walletaccounts-system

**Comment by Semisol** [comment]
I have contacted but no response. Can you check?
