### ISSUE TITLE
LN tickets issues

### ISSUE THREAD

**Issue by Semisol** [lnbits/lnbits-legend#548]
- Trying to change the wallet after creation fails with "Not your form".
- Sometimes, the form breaks so that you cannot change between flat rate or per word rate after creation.
- Ticket contents may be too long, causing them to be hard to read since it requires horizontal scrolling. (idea: add an external view option, and don't show the content in the list?)
- Zero price results in a zero value invoice. (idea: show no invoice, or deny setting it below 1 sat)

**Comment by arcbtc** [comment]
Yeah, first isn't fixable, last is a bug

**Comment by arcbtc** [comment]
Fixed bug https://github.com/lnbits/lnbits-legend/commit/ffba97850b9caf207925d524aa4d18cdfaa76c85
