### ISSUE TITLE
Zero value invoices result in "NaN sats" showing up

### ISSUE THREAD

**Issue by Semisol** [lnbits/lnbits-legend#549]
Attempting to pay a zero value invoice results in "NaN sats"
<img width="491" alt="image" src="https://user-images.githubusercontent.com/45574030/156301217-05a6e913-aa8d-4928-bcd6-9bb9e9c07e37.png">

**Comment by arcbtc** [comment]
Due to some security concerns we dont currently support generating or paying 0 invoices

**Comment by Semisol** [comment]
> Due to some security concerns we dont currently support generating or paying 0 invoices

Understandable, but showing a proper popup would be more useful. Sorry for the late reply.
