### ISSUE TITLE
Dependency hell

### ISSUE THREAD

**Issue by petrkr** [lnbits/lnbits-legend#563]
In short version:
LNBits needs anyio in version 3.3.1, but it also requires purerpc package to connect to LND, but this package need anyio in version 1.x.x

What is solution for this dependency hell?
```
  Attempting uninstall: anyio
    Found existing installation: anyio 1.4.0
    Uninstalling anyio-1.4.0:
      Successfully uninstalled anyio-1.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
purerpc 0.6.1 requires anyio<2,>=1.0.0, but you have anyio 3.3.1 which is incompatible.
```

**Comment by arcbtc** [comment]
Is this after the last update?

**Comment by arcbtc** [comment]
no doesnt look like it. Goodness. Will investigate

**Comment by petrkr** [comment]
I using now tag 0.7.0, but same issue was in 0.4.0 tag, and since in master branch it is same requirement.txt and it is still 3.x.x and purerpc want 1.x.x, then it would lead to same issue.. Actually I just noticed PureRPC have bug report about that too already https://github.com/standy66/purerpc/issues/31

**Comment by petrkr** [comment]
Solution would be use 1.x.x anyio or do not use purerpc until they fix that...

**Comment by fusion44** [comment]
This is because the README still says that `purerpc` is required. I've removed the requirement for this dead package some time ago. I think I had also updated the README alongside the removal. I'll fix the README. Sorry about that.

Quick fix: install `grpcio` instead of `purerpc` and you should be good to go.
