### ISSUE TITLE
Create Invoice - LndRestWallet - AttributeError: 'NoneType' object has no attribute 'wallet_id'

### ISSUE THREAD

**Issue by PrinzMonty** [lnbits/lnbits-legend#599]
Hi,

when I create an "Invoice" I get the following error. Can anyone reproduce this? 

```
lnbits-legend |   File "./lnbits/core/views/api.py", line 375, in api_payment
lnbits-legend |     await check_invoice_status(payment.wallet_id, payment_hash)
lnbits-legend | AttributeError: 'NoneType' object has no attribute 'wallet_id'
lnbits-legend | ERROR:    Exception in ASGI application
```

```
lnbits-legend |   File "./lnbits/core/views/api.py", line 375, in api_payment
lnbits-legend |     await check_invoice_status(payment.wallet_id, payment_hash)
lnbits-legend | AttributeError: 'NoneType' object has no attribute 'wallet_id'
```

I run LNbits with Docker over a Tor Proxy & connected to my Raspiblitz.

Raspiblitz Version: 1.7.2
LNbits Version: main (last)
Deployment: Docker on localhost

**Comment by callebtc** [comment]
Hello,
thank you for submitting an issue. To be able to help, we would need very specific information. Please provide the exact version of LNbits you're running, and **an exact step by step** description of how to produce this error. Appreciated 🙏

**Comment by PrinzMonty** [comment]
LNbits Version: main branch / 2f381960

Hi,

1. I have started LNbits locally with Docker
2. I have connected to my Raspiblitz via TOR, for this I have changed the source code a bit to work with SOCKS5. (https://github.com/PrinzMonty/lnbits-legend/commit/f0bb470b74343159c76da26ab7cce3e620942c52)

_However, I will test it again without my change (TOR), although it is not clear to me why this would cause my error above. Basic support for TOR on LndRestWallet would also be desirable. I've only been learning Python for 5 days, so I'm hoping I might be able to solve it better myself._

3. On startup, I see that there is a connection to my LND node. Also when creating in the LNbits UI it works.

4. I press "CREATE INVOICE" and get the error from above on the console. There is nothing in the browser DEV tools and I do not get a message in LNbits UI.

So the question is, is it now because of my modification for the SOCKS5 connection, or is there something wrong with the LndRestWallet interface?

**Comment by callebtc** [comment]
Is an invoice created and can you pay it successfully? It seems to fail at the invoice check after creating one.

**Comment by PrinzMonty** [comment]
No, this is not possible, I click on "Create Invoice" and get `AttributeError: 'NoneType' object has no attribute 'wallet_id'` in the log.

Do you have a tip how I could debug it better?

**Comment by dni** [comment]
what the heck? https://github.com/lnbits/lnbits-legend/blob/main/lnbits/core/views/api.py#L374
this has to be a bug, payment is fetched on line 374 and line 376 but only check if it exists on the second one?!

**Comment by caglorithm** [comment]
> Do you have a tip how I could debug it better?

Yes! First, have a look in your terminal, it should say which endpoint was called before the error. If the `payment_hash` is none or wrong, then the function will fail (like in your case). If this is the case, next we would need to figure out why there is no `payment_hash`. 

If you don't see anything in the log, you can go into `./lnbits/core/views/api.py", line 375` and put a `print(payment_hash)` before the line that crashes to see if it's `None`.

**Comment by PrinzMonty** [comment]
I put the log in the attachment, and print(payment_hash) returns an "undefined".

[lnbits-log.txt](https://github.com/lnbits/lnbits-legend/files/8512806/lnbits-log.txt)

**Comment by dni** [comment]
so that means your post request is already failing with a more interesting error, before the polling GET requests fails in that way

**Comment by PrinzMonty** [comment]
This is certainly useful, but the payment_hash doesn't seem to get any value in my case. So it must have gone wrong before.

`INFO:     10.30.0.1:36488 - "GET /api/v1/payments/undefined HTTP/1.1" 200 OK`

**Comment by callebtc** [comment]
Yup, that's what I thought. The error is probably earlier in the invoice creation of the wallet itself. Can you please make sure that you're running the newest LNbits before we go on? Thanks!

**Comment by PrinzMonty** [comment]
I updated the source to the latest one but the errors are the same.

**Comment by arcbtc** [comment]
Sounds like you're not using the right macaroon
Can you connect to a different funding source like lntxbot or legend.lnbits.com, then you can isolate it being an issue with your connection to lnds restapi

**Comment by PrinzMonty** [comment]
It was my LND node that something was wrong with. I had to set it up again and now it works.

Thanks for the help!
