### ISSUE TITLE
Extension webhooks missing

### ISSUE THREAD

**Issue by nanda77** [lnbits/lnbits-legend#605]
Is it possible to add webhooks for LNURLw, paywalls, Tpos...? I mean how will I know instantly if someone withdraws or makes a payment using paywall or Tpos...    

As Ben Arc suggested.... Since transactions have webhook field, all extensions should use it.

**Comment by bezysoftware** [comment]
Agreed, especially LNURLw should have a webhook, you really wanted to be notified when somebody uses it

**Comment by callebtc** [comment]
Thank you for the PR!
