### ISSUE TITLE
LNURL - Does not work - 426 UPGRADE REQUIRED

### ISSUE THREAD

**Issue by PrinzMonty** [lnbits/lnbits-legend#606]
LNURL does not work, but I use a domain with https.

```
LNURLs need to be delivered over a publically accessible `https` domain or Tor.
426 UPGRADE REQUIRED
```
<- Which connection are we talking about here, the domain through which LNbits is accessible or the connection to the LND Rest Api?

I have also shared the TLS certificate on my local node so that my DNS name is accessible from the outside. 

I run a local node with Raspiblitz, without TOR, this I tunnel via an OpenVPN server to a public IP. 

On the public IP I have set a top-level domain that works with the TLS certificate of the LND node, which I have stored in the LNbits settings under "LND_REST_ENDPOINT=". This works so far, except for the LNURL part.

I'm not sure where the error is or if it even works that way with my VPN tunnel?  But maybe I still do not really understand how LNurl works?!

Log:

```
...
lnbits-legend  |     dependant=dependant, values=values, is_coroutine=is_coroutine
lnbits-legend  |   File "/opt/venv/lib/python3.7/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
lnbits-legend  |     return await dependant.call(**values)
lnbits-legend  |   File "./lnbits/extensions/withdraw/views_api.py", line 110, in api_link_create_or_update
lnbits-legend  |     return {**link.dict(), **{"lnurl": link.lnurl(req)}}
lnbits-legend  |   File "./lnbits/extensions/withdraw/models.py", line 55, in lnurl
lnbits-legend  |     return lnurl_encode(url)
lnbits-legend  |   File "/opt/venv/lib/python3.7/site-packages/lnurl/core.py", line 26, in encode
lnbits-legend  |     raise InvalidUrl
lnbits-legend  | lnurl.exceptions.InvalidUrl
```

**Comment by PrinzMonty** [comment]
Ohhh common!

I have misconfigured my NGINX proxy. Now it works! 

If anyone is facing this problem, feel free to test my configuration.

```
        location / {
                proxy_pass http://<LNbits_IP>:5000;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header Host $host;
                proxy_http_version 1.1;
        }
```

**Comment by jjmmbb** [comment]
I'm encountering an error 426 while trying to access pay links. Despite the fact that it's accessible via HTTPS, this error continues to appear. Has anyone found a solution to this issue?

**Comment by motorina0** [comment]
> Has anyone found a solution to this issue?
It might be a problem on your side. See OP solution.
