### ISSUE TITLE
issue with LNURLw

### ISSUE THREAD

**Issue by massmux** [lnbits/lnbits-legend#612]
with latest lnbits installed in docker. proxied to public https url with nginx. all works fine. but the extension LNURLw does not work. the result it returns is: "LNURLs need to be delivered over a publically accessible `https` domain or Tor.
426 UPGRADE REQUIRED"
while the system is in https

installing the older version (lnbitsdocker/lnbits:latest), it works smoothly.

**Comment by ElucGeek** [comment]
Hi, I have he same issue here. Did anyone solve this without downgrading?

**Comment by massmux** [comment]
After many tests and thanks also to messages i found on various sources, i found a way to resolve.

Add the following environment variable
      FORWARDED_ALLOW_IPS: "*"
as environment variable. both if you use docker or standard install.

hope this helps

**Comment by massmux** [comment]
I am going to close this issue since, the solution i provided is working fine and resolves the problem shown at beginning of this thread.

**Comment by jjmmbb** [comment]
I'm encountering an error 426 while trying to access pay links. Despite the fact that it's accessible via HTTPS, this error continues to appear. Has anyone found a solution to this issue?

**Comment by vcavallo** [comment]
This problem persists even with the addition of the FORWARDED_ALLOW_IPS env variable.
