### ISSUE TITLE
Add balance to new wallet

### ISSUE THREAD

**Issue by rasodu** [lnbits/lnbits-legend#635]
Is there a way to assign a balance to brand new wallet?

I have balance in LND. I would like to spend it thru LNBits wallet.
But currently LNBits it telling me that I don't have sufficient balance.

I am using Postgres backend. So, I don't mind making DB changes directly.

**Comment by talvasconcelos** [comment]
Hi, you need to either send funds to your LNbits wallet with an invoice, or set yourself as admin, and on your wallet a small "plus" sign will show up, next to the balance that allows you to top up the wallet!

**Comment by rasodu** [comment]
There is no authentication to access any of the wallets.
Is it safe to enable admin wallet?
Is there any way to enable authentication?

**Comment by callebtc** [comment]
For the time being, the wallet URL serves for authentication. There is a key in the URL, so you need to keep that private. It is safe to enable admin wallet, as long as you don't share the URL. 

Alternatively, you could also modify a transaction into the db manually that credits you: Create an invoice, go to `apipayments` table and set `pending=0`.

Hope this helps! Closing.

**Comment by rasodu** [comment]
Sounds good. Thanks
