### ISSUE TITLE
"Tip us" paywall link in README is broken

### ISSUE THREAD

**Issue by Entryist** [lnbits/lnbits-legend#664]
The README [Tip us section](https://github.com/lnbits/lnbits-legend#tip-us) links to a [dead paywall](https://lnbits.com/paywall/GAqKguK5S8f6w5VNjS9DfK) with a 404 error.

**Comment by callebtc** [comment]
@arcbtc needs to update the link to `legend.*`

**Comment by callebtc** [comment]
Duplicate of #647. Closing.
