### ISSUE TITLE
Withdraw from a Legend wallet doesn't work. 

### ISSUE THREAD

**Issue by felipebrunet** [lnbits/lnbits-legend#695]
I sent 2 sats successfully in. Then I tried to withdraw 1 sat, using all means (invoice, empty invoice, lnurl, ln address) but got the same error:
500 internal error.
![error lnbits legend 1](https://user-images.githubusercontent.com/40004928/176804979-34b76681-5c2c-4e1f-ac81-80acec1005c9.png)
In a second attempt I got another error.
![error lnbits legend 2](https://user-images.githubusercontent.com/40004928/176804984-8bae8bcf-99b5-48b7-9805-b3b32c81c863.png)
Did I do something wrong or something I missed?
Thanks!

**Comment by talvasconcelos** [comment]
There's a minimum reserve that your wallet must have to ensure it can cover
transaction fees!

**Comment by felipebrunet** [comment]
Sorry, my bad. Indeed it worked perfectly with a few more sats.
This is awesome. Thanks!!!

**Comment by nolim1t** [comment]
Similar to https://github.com/lnbits/lnbits-legend/issues/552 ?
