### ISSUE TITLE
Global webhook

### ISSUE THREAD

**Issue by nanda77** [lnbits/lnbits-legend#723]
Isn't it better lnbits has a webhook(per wallet or per lnbits instance) for every transaction that takes place? ..... That way we don't need webhook for each and every extension?

**Comment by callebtc** [comment]
You can already do that for invoices, just add the `webhook` to the data field. Can you please elaborate your issue in more detail?

**Comment by nanda77** [comment]
I mean having one webhook or subscription of events is required for each user wallet when there is a change in event.... that way we don't need webhooks for every extension.... right now if a 3rd party wants to use any lnbits extension into their project, they will be needing webhooks which many extensions do not support.   Invoice webhooks can only be used when creating invoices, not when extension creates invoices.

**Comment by callebtc** [comment]
Nope, webhooks should stay on demand only. 

If you need it in a specific place where it is not supported, please feel free to report in am issue or PR!
