### ISSUE TITLE
(#725) should write lightning:LNURL instead of LNURL to NFC-Tag

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnbits-legend#752]
for the sake of UX. Cant code, have no idea how to include it though 😅😂

**Comment by callebtc** [comment]
@leesalminen what do you think? 

The current implementation seems to trigger lightning wallets in my phone already but adding a custom `lightning:` URI might be better for more compatibility. Any opinions on this?

**Comment by arbadacarbaYK** [comment]
no then meaning with Lightning:LNURLXXXX

**Comment by arbadacarbaYK** [comment]
Without Lightning:
+ Most wallets are shown as a selection to choose from
- some (Muun and Breez) only react when already opened and  tapped (iphone11) and do not show up in the list
- Having no wallet installed i am redirected to lnbits 

With Lighting:
+ All wallets show up in the list
- Havin no wallet installed nothing happens at all

Some want to be triggered explicitly 👸🏻

Is there a reason why this is not already the case for all QRs shown / to be printed ?

**Comment by arbadacarbaYK** [comment]
not so happy with LNURLw-prefix #761 because LUD17 is so far just supported by only a few wallets whereas lightning: works fine for all 😅

**Comment by callebtc** [comment]
[I completely agree](https://github.com/lnbits/lnbits-legend/pull/762) 🤬
