### ISSUE TITLE
lnurl auth not working

### ISSUE THREAD

**Issue by sawrubgupta** [lnbits/lnbits-legend#755]
Hey I am trying to login in lnmarkets but not able to do so, as it giving me 500 errors
lnmarkets wbsite link :- https://lnmarkets.com/

**Comment by dni** [comment]
we have fixed this recently, are you up to date on main branch?

**Comment by dni** [comment]
ok, @talvasconcelos is on it, there is a branch with a fix https://github.com/lnbits/lnbits-legend/tree/fix/lnurlAuth but it never got mergen.
