### ISSUE TITLE
Fiat price param when creating Invoice

### ISSUE THREAD

**Issue by nanda77** [lnbits/lnbits-legend#793]
Hi Guys!

I know that BTC is the future of currency but we are not there yet, so I think its better we give an optional extra param to add fiat price/value when creating an invoice similar to webhook?   Will help merchants a lot.

**Comment by callebtc** [comment]
This is already possible, you can use the `unit` param when creating an invoice. Please have a look at the API description at the righthand bar in the interface! Closing.
