### ISSUE TITLE
Add 'copy invoice' button to the TPOS check out page. 

### ISSUE THREAD

**Issue by btcnym** [lnbits/lnbits-legend#838]
Similar to the button on the tip jar and the satspay check out pages

Missing:
![image](https://user-images.githubusercontent.com/61063552/182725559-f407917b-fb58-4ef8-866b-410079f50609.png)

Good:
![image](https://user-images.githubusercontent.com/61063552/182725699-7dd3f0b1-5a78-4f97-8b90-42b15874165c.png)

Thanks!

**Comment by callebtc** [comment]
Concept ACK
