### ISSUE TITLE
lnurl auth using wallet id 

### ISSUE THREAD

**Issue by sawrubgupta** [lnbits/lnbits-legend#841]

**Comment by sawrubgupta** [comment]
Hey I have looked into  codes of other wallets for lnurl auth,  it seems to be most of them uses admin key as the key to generate the linking key, but because of this interoperability problem is coming, for example, if I use alby as an wallet and paste my admin key there, it create a different user than what lnbits is creating, mean same admin key is creating two different users which is quite bad for interoperability, we need to use admin key for linking key generation, not the wallet id.

this is how alby is genrating key - `let keyHex = sha256(lnbits://${this.config.adminkey}).toString(Hex);`

Some links where they implement lnurl auth [zeusLink](https://github.com/ZeusLN/zeus/blob/master/views/LnurlAuth.tsx#L99-L122) [alby1Link](https://github.com/getAlby/lightning-browser-extension/blob/a5351e8811366035cb7be30e9383eb5c504bd522/src/extension/background-script/connectors/lndhub.ts#L285-L290) [alby2Link](https://github.com/getAlby/lightning-browser-extension/blob/master/src/common/utils/signer.ts) 

I think we have to use the same style as bluewallet - the goal is that all apps/clients use the same format and are interoperable
lndhub - used by bluewallet and zeus use that format.

that format would suggest: “[appname]://[private credentials] 
=> “lnbits://admin-key

e.g. as bluewallet and alby do it: [link](https://github.com/BlueWallet/BlueWallet/blob/f105acb0b67a11079e756d586d4712ed485262f0/class/wallets/lightning-custodian-wallet.js#L113)

**Comment by callebtc** [comment]
Concept NACK

1) LNURL-auth is not designed to be interoperable. 
2) The suggested fix would merely make LNbits auth compatible with Alby but with nothing else.
3l It would be a **very** bad idea to change the linking key now and break all past auth's for all existing users.

**Comment by bumi** [comment]
yes, it is actually pretty complex to try to have lnurl-auth for custodial wallets interoperable. 
at Alby we tried to do that and made a few changes over the time for that. in a few conversations we also hoped that this scheme`lndhub://[credentials]` could be a standard and help with interoperability. 

but yeah it's hard and having that backwards compatible is tricky. 

I think services implementing lnurl-auth should allow users to have multiple keys. This solves this problem and reduces the need that wallets should be interoperable and also gives users the chance to change they linked keys. kollider does it like this for example. The bitcoin design guide (preview) also mentions that: https://deploy-preview-885--bitcoin-design-site.netlify.app/guide/sign-in-with-bitcoin/#connecting-multiple-wallets (preview)
