### ISSUE TITLE
empty post requests throwing internal server errors

### ISSUE THREAD

**Issue by dni** [lnbits/lnbits-legend#847]
the following testcase errors. it should work on all post endpoints

```python
@pytest.mark.asyncio
async def test_what(client):
    url = "/copilot/api/v1/copilot"
    response = await client.post(url)
```

error:
```
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL:
        SELECT *, COALESCE((SELECT balance FROM balances WHERE wallet = wallets.id), 0) AS balance_msat
        FROM wallets
        WHERE adminkey = ? OR inkey = ?
        ]
[parameters: (Security(APIKeyQuery), Security(APIKeyQuery))]
```

it does work on legend server.
![screenshot-1659681456](https://user-images.githubusercontent.com/1743657/183018993-ef2217af-ea9c-40f5-aae1-808b6760e7b3.jpg)

**Comment by callebtc** [comment]
The PR in #848 should include the fix for this issue. If the error is thrown in the crud I guess it should have never reached it.
