### ISSUE TITLE
Extra{} field in body not taking input when paying an Invoice using api. 

### ISSUE THREAD

**Issue by nanda77** [lnbits/lnbits-legend#858]
While creating an invoice using api, the extra{} field is working but does not work when paying an invoice. If it works in both ways, it will help me pass fiat values during a transaction and fetch this to show fiat values in frontend.

**Comment by callebtc** [comment]
This is intentional behaviour. Extra is only for creating invoices right now. A PR implementing this could be interesting.

**Comment by nanda77** [comment]
I want to pass on the fiat usd prices in extra field during the time of payment, so I can show the fiat equivalent value in transaction history of dashboard.

**Comment by callebtc** [comment]
You can write a PR
