### ISSUE TITLE
Webhook "not sent yet" when an invoice is paid

### ISSUE THREAD

**Issue by massmux** [lnbits/lnbits-legend#924]
When an invoice is paid the webhook is not triggered when invoice is paid. from lnbits when clicking on the paid invoice, a blue label is shown with "not sent yet" and this remains the same forever.
thank you for your attention

**Comment by callebtc** [comment]
Hi, are you using the newest version of lnbits? Which backend and which database are you using?

**Comment by massmux** [comment]
database is sqlite, backend is LND on voltage. this same configuration worked until 10 days ago.
version was updated around 1 month ago

**Comment by massmux** [comment]
sorry, you can close this issue. i just have seen that in the very last version, this problem seems fixed. just tested.

**Comment by Rednas07** [comment]
I have the same problem. A blue label showing "not sent yet", even after the request is paid. Im using LND on voltage.
