### ISSUE TITLE
Ticket Counter Broken

### ISSUE THREAD

**Issue by manakill** [lnbits/lnbits-legend#926]
Test bought 2 tickets. Amount available didn't decrease. Amount Sold didn't increase...
![2022-08-24 22_43_47-LNbits — Mozilla Firefox](https://user-images.githubusercontent.com/9597295/186563808-2e7f4d33-66e0-45f6-8658-37821791ff32.png)

**Comment by leesalminen** [comment]
Taking a look at `extensions/events`, it looks like the CRUD method `set_ticket_paid` is never called. It's been commented out in the extension. Wonder if there's a reason this was taken out or just an oversight?
